# Generated by Django 5.2.7 on 2025-12-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='filetype',
            field=models.FileField(max_length=30, upload_to=''),
        ),
    ]
