# Generated by Django 5.2.7 on 2025-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_description_alter_notes_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='filetype',
            field=models.FileField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
