# Generated by Django 5.2.7 on 2025-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_filetype_alter_notes_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='filetype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
