# Generated by Django 5.2.7 on 2025-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_description_alter_notes_filetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
