# Generated by Django 5.2.7 on 2025-12-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notes_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
