# Generated by Django 5.2.7 on 2025-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_notes_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
